/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;
import java.io.IOException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import libarysystem.Book;
import libarysystem.Serialization;
import libarysystem.SetOfBooks;
/**
 *
 * @author Thilina
 */
public class Books extends javax.swing.JFrame {

    /**
     * Creates new form Books
     */
    
     private SetOfBooks holdings=new SetOfBooks();
    SetOfBooks searchList=new SetOfBooks();
    
    public static final String FILE_NAME_BOOKS = "Books.txt";
  public static final String FILE_NAME_MEMBERS = "Members.txt";
  
         int timeRun=0;
    public Books() {
        initComponents();
        try { 
            for(Book book : Serialization.deserializeBooks())
            {
                holdings.addBook(book);
            }
        } catch (IOException | ClassNotFoundException ex) {
             
        }
         //table load in search page
         TableLoad(tbInfoTable,holdings);
          //table load in update page
         TableLoad(tbInfo1Table,holdings);
        ////////////////////////////////////////////////////////////////////////
        
         currentDate();
        
        new Thread()
        {
        public void run()
        {
        while(timeRun==0)
        {
            Calendar cal=new GregorianCalendar();
            
            int hour=cal.get(Calendar.HOUR);
            int minute=cal.get(Calendar.MINUTE);
            int second=cal.get(Calendar.SECOND);
            int AM_PM=cal.get(Calendar.AM_PM);
            String day_night=" ";
            
            if(AM_PM==1)
        {
            day_night="PM";
        }
            else
        {
            day_night="AM";
        }
            
            String time= hour+":"+minute+":"+second+" "+day_night;
            showtime.setText(time);
        }
        }
        
        }.start();  
        
        ////////////////////////////////////////////////////////////////////////
        
    }
     //show date
    public void currentDate(){

                    Calendar cal=new GregorianCalendar();
                    int month=cal.get(Calendar.MONTH);
                    int year=cal.get(Calendar.YEAR);
                    int day=cal.get(Calendar.DAY_OF_MONTH);
                    showdate.setText(year+"-"+(month+1)+"-"+day);
               }
    
    
    //////////////////////////////////////////////////////////////

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        titleRadio = new javax.swing.JRadioButton();
        authorRadio = new javax.swing.JRadioButton();
        ISBNRadio1 = new javax.swing.JRadioButton();
        AccessionNumberRadio = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbInfoTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtISBN = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        btnInsertNewBook = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblUpID = new javax.swing.JLabel();
        txtUpdateISBN = new javax.swing.JTextField();
        txtUpdateTitle = new javax.swing.JTextField();
        txtUpdateAuthor = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbInfo1Table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        showtime = new javax.swing.JLabel();
        showdate = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Enter Book Details : ");

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        buttonGroup1.add(titleRadio);
        titleRadio.setText("Title");

        buttonGroup1.add(authorRadio);
        authorRadio.setText("Author");

        buttonGroup1.add(ISBNRadio1);
        ISBNRadio1.setText("ISBN No");

        buttonGroup1.add(AccessionNumberRadio);
        AccessionNumberRadio.setText("Accession Number");

        tbInfoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Accession Number", "ISBN Number", "Title", "Author"
            }
        ));
        jScrollPane1.setViewportView(tbInfoTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(titleRadio)
                        .addGap(18, 18, 18)
                        .addComponent(authorRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ISBNRadio1)
                        .addGap(10, 10, 10)
                        .addComponent(AccessionNumberRadio))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleRadio)
                    .addComponent(authorRadio)
                    .addComponent(ISBNRadio1)
                    .addComponent(AccessionNumberRadio))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Serch Books", jPanel2);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("ISBN No : ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Name :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Author:");

        btnInsertNewBook.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnInsertNewBook.setText("Add New Book");
        btnInsertNewBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertNewBookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtISBN))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53)
                .addComponent(btnInsertNewBook)
                .addGap(281, 281, 281))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5)
                        .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnInsertNewBook))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Books", jPanel3);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Accession Number :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("ISBN Number :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Title :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Author :");

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });

        tbInfo1Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Accession Number", "ISBN Number", "Title", "Author"
            }
        ));
        tbInfo1Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbInfo1TableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbInfo1Table);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblUpID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtUpdateISBN)
                            .addComponent(txtUpdateTitle)
                            .addComponent(txtUpdateAuthor, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblUpID, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtUpdateISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtUpdateTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtUpdateAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addComponent(btnDelete)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Delete Book", jPanel4);

        jPanel1.add(jTabbedPane1);
        jTabbedPane1.setBounds(20, 100, 820, 390);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagers/homeButton.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(0, 0, 90, 83);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagers/logo.png"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(290, 0, 280, 90);

        showtime.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        showtime.setText("..");
        jPanel1.add(showtime);
        showtime.setBounds(700, 10, 130, 30);

        showdate.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        showdate.setText("..");
        jPanel1.add(showdate);
        showdate.setBounds(680, 50, 150, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagers/bkground.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 860, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 863, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        
        if(txtSearch.getText().toString() != "")
 {
        if(titleRadio.isSelected())
        {
           searchList=holdings.findBookByTitle(txtSearch.getText().toString());
           searchTableLoad(searchList); 
        }
        else if(authorRadio.isSelected())
        {
            searchList=holdings.findBookByAuthor(txtSearch.getText().toString());
               searchTableLoad(searchList); 
        }
        else if(ISBNRadio1.isSelected())
        {
                searchList=holdings.findBookFromISBN(txtSearch.getText().toString());
                searchTableLoad(searchList); 
            
        }
        else if(AccessionNumberRadio.isSelected())
        {
            if(!txtSearch.getText().equals(""))
            {
           
               searchList=holdings.findBookFromAccNumber(txtSearch.getText());
          
               searchTableLoad(searchList); 
            }   
               
        }
 } 
        
        
    }//GEN-LAST:event_txtSearchKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        LibaryHome l=new LibaryHome();
        l.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed
//insert Books
    private void btnInsertNewBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertNewBookActionPerformed
        // TODO add your handling code here:
        
        //first check the filds are valied
 if (txtAutor.getText().trim() == null || txtName.getText().trim() == null || !isInt(txtISBN.getText())) {

            JOptionPane.showMessageDialog(this, "Invalied Data !!");
            return;

        }

        // show a confirmation message box to user
        int i = JOptionPane.showConfirmDialog(this, "Do you want to continue?", "Add Data", JOptionPane.NO_OPTION);

        if (i != 0) {

            return;
        }
       
        holdings.addBook(new Book(txtName.getText().toString(),txtISBN.getText().toString(),txtAutor.getText().toString()));
              boolean isok =true;
        try{
            Serialization.Serialize(holdings,FILE_NAME_BOOKS);
            
            for (Book book : Serialization.deserializeBooks()) 
            {
		System.out.println(book);
            }
              isok =true;
          }
          catch(Exception ex)
          {
                   isok =false;
          }
          
   

        if (isok == true) {

            JOptionPane.showMessageDialog(this, "Data Added!!");
            // clear all fields
            txtISBN.setText(null);
            txtAutor.setText(null);
            txtName.setText(null);
            //table load in search page
         TableLoad(tbInfoTable,holdings);
          //table load in update page
         TableLoad(tbInfo1Table,holdings);

        } else {

            JOptionPane.showMessageDialog(this, "Unsuccessful Process");
        }
        
        
    /////////////////////////////////////////////////////////////////////    
    }//GEN-LAST:event_btnInsertNewBookActionPerformed

    private void tbInfo1TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbInfo1TableMouseClicked
        // TODO add your handling code here:
           // get selected row
        int row = tbInfo1Table.getSelectedRow();

        lblUpID.setText(tbInfo1Table.getValueAt(row, 0).toString());
        txtUpdateISBN.setText(tbInfo1Table.getValueAt(row, 1).toString());
        txtUpdateTitle.setText(tbInfo1Table.getValueAt(row, 2).toString());
        txtUpdateAuthor.setText(tbInfo1Table.getValueAt(row, 3).toString());
        
        /////////////////////////////////////
    }//GEN-LAST:event_tbInfo1TableMouseClicked

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        // TODO add your handling code here:
         if (lblUpID.getText().equals("--")) {

            JOptionPane.showMessageDialog(this, "Please select a book to Delete");
            return ;
        }
        int response = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this book?", "Confirm",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION)
        {
            Book book=holdings.findBookFromAccNumber(lblUpID.getText()).firstElement();
            if(book.isOnLoan())
            {
                JOptionPane.showMessageDialog(rootPane, "Book cannot be deleted. Book is on Loan !");
            }
            else
            {
                holdings.removeBook(book);

                //table load in search page
                TableLoad(tbInfoTable,holdings);
                //table load in update page
                TableLoad(tbInfo1Table,holdings);

                try {
                    Serialization.Serialize(holdings,"Books.txt");
                }
                catch (Exception ex) {

                }
                JOptionPane.showMessageDialog(rootPane, "Book is been deleted successfully !");
                // clear all fields

                txtUpdateTitle.setText(null);
                txtUpdateISBN.setText(null);
                txtUpdateAuthor.setText(null);
                lblUpID.setText("--");
            }
        }

        else
        {
            JOptionPane.showMessageDialog(this, "Delete Unsuccessful");
        }
        
        
        ////////////////////////////////
    }//GEN-LAST:event_btnDeleteMouseClicked
     //display search results
    public void searchTableLoad(SetOfBooks searchList)
    {
        String[] colName = { "Accession Number", "ISBN Number", "Title", "Author "};
            Object[][] object = new Object[searchList.size()][4];
            System.out.println(searchList.size());
            int i = 0;
            if (searchList.size() != 0) {
                for (Book book : searchList) {
                    object[i][0] = book.getAccessionNumber();
                    object[i][1] = book.getISBNNumber();
                    object[i][2] = book.getTitle();
                    object[i][3] = book.getAuthor();
                    i++;
                  
                }    
            }
            DefaultTableModel model = new DefaultTableModel(object,colName)
                    {
    public boolean isCellEditable(int row, int column)
    {
      return false;//This causes all cells to be not editable
    }
  };
            tbInfoTable.setModel(model);
            tbInfoTable.setRowSorter(new TableRowSorter<TableModel> (model));
            tbInfoTable.setAutoscrolls(true);
            tbInfoTable.getTableHeader().setReorderingAllowed(false);
        
    }
  
    //////////////////////////////////////////////////////////
     /*tableload*/
    public void TableLoad(JTable table,SetOfBooks holdings)
    {
        String[] colName = { "Accession Number", "ISBN Number", "Title", "Author "};
            Object[][] object = new Object[ holdings.size()][4];
            int i = 0;
            if ( holdings.size() != 0) {
                for (Book book :  holdings) {
                    object[i][0] = book.getAccessionNumber();
                    object[i][1] = book.getISBNNumber();
                    object[i][2] = book.getTitle();
                    object[i][3] = book.getAuthor();
                    i++;
                  
                }    
            }
            
            DefaultTableModel model = new DefaultTableModel(object,colName)
                    {
    public boolean isCellEditable(int row, int column)
    {
      return false;//This causes all cells to be not editable
    }
  };
            table.setModel(model);
            table.setRowSorter(new TableRowSorter<TableModel> (model));
            table.setAutoscrolls(true);
            table.getTableHeader().setReorderingAllowed(false);
        
    }
    
    ////////////////////////////////////////////////////////////
        /*check that string is number(int)
    
    */
    public static boolean isInt(String text) {


        try {

            int i = Integer.parseInt(text);

            return true;

        } catch (Exception ex) {

            System.out.println("VALIDATE EXCEPTION -- > " + ex.getMessage());
            return false;
        }
    }
    
    /////////////////////////////////////////////////////////////
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Books().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AccessionNumberRadio;
    private javax.swing.JRadioButton ISBNRadio1;
    private javax.swing.JRadioButton authorRadio;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsertNewBook;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblUpID;
    private javax.swing.JLabel showdate;
    private javax.swing.JLabel showtime;
    private javax.swing.JTable tbInfo1Table;
    private javax.swing.JTable tbInfoTable;
    private javax.swing.JRadioButton titleRadio;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtUpdateAuthor;
    private javax.swing.JTextField txtUpdateISBN;
    private javax.swing.JTextField txtUpdateTitle;
    // End of variables declaration//GEN-END:variables
}
