/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;
import javax.swing.ImageIcon;
import AppPackage.AnimationClass;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.ImageIcon;

/**
 *
 * @author Thilina
 */
public class LibaryHome extends javax.swing.JFrame {
  AnimationClass AC=new AnimationClass();
    /**
     * Creates new form LibaryHome
     */
  int timeRun=0;
    public LibaryHome() {
        initComponents();
        SlideShow();
          ////////////////////////////////////////////////////////////////////////
        
         currentDate();
        
        new Thread()
        {
        public void run()
        {
        while(timeRun==0)
        {
            Calendar cal=new GregorianCalendar();
            
            int hour=cal.get(Calendar.HOUR);
            int minute=cal.get(Calendar.MINUTE);
            int second=cal.get(Calendar.SECOND);
            int AM_PM=cal.get(Calendar.AM_PM);
            String day_night=" ";
            
            if(AM_PM==1)
        {
            day_night="PM";
        }
            else
        {
            day_night="AM";
        }
            
            String time= hour+":"+minute+":"+second+" "+day_night;
            showtime.setText(time);
        }
        }
        
        }.start();  
        
        ////////////////////////////////////////////////////////////////////////
        
        
    }

    /////////////////////////////////////////////////////////////////////////
    //show date
    public void currentDate(){

                    Calendar cal=new GregorianCalendar();
                    int month=cal.get(Calendar.MONTH);
                    int year=cal.get(Calendar.YEAR);
                    int day=cal.get(Calendar.DAY_OF_MONTH);
                    showdate.setText(year+"-"+(month+1)+"-"+day);
               }
    
    
    //////////////////////////////////////////////////////////////
    //////////////////////////////////////////////////////
    
   //Animation Slide show is done here
       private void SlideShow(){
       new Thread(){
       int count;
     
       
       public void run(){
       
           try{
           while(true){
           switch(count){
               case 0:
                   ImageIcon II0=new ImageIcon(getClass().getResource("/Imagers/image4.jpg"));
                   image1.setIcon(II0);
                   Thread.sleep(3000);
                   AC.jLabelXLeft(0, -900, 10, 9, image1);
                   AC.jLabelXLeft(900, 0, 10, 9, image2);
                   count= 1;
                   break;
                   
               case 1:
                   ImageIcon II1=new ImageIcon(getClass().getResource("/Imagers/image2.jpg"));
                   image2.setIcon(II1);
                   Thread.sleep(3000);
                   AC.jLabelXRight(-900, 0, 10, 9, image1);
                   AC.jLabelXRight(0, 900, 10, 9, image2);
                   count= 2;
                   break;
                   
                case 2:
                   ImageIcon II2=new ImageIcon(getClass().getResource("/Imagers/image5.jpg"));
                   image1.setIcon(II2);
                   Thread.sleep(3000);
                   AC.jLabelXLeft(0, -900, 10, 9, image1);
                   AC.jLabelXLeft(900, 0, 10, 9, image2);
                   count=3;
                   break;
                       
                case 3:
                   ImageIcon II3=new ImageIcon(getClass().getResource("/Imagers/image6.jpg"));
                   image2.setIcon(II3); 
                   Thread.sleep(3000);
                   AC.jLabelXRight(-900, 0, 10, 9, image1);
                   AC.jLabelXRight(0, 900, 10, 9, image2);
                   count=0;
                   break;

                                       
           }
          }
           
           }
           
           catch(Exception e){}
       }
        }.start();
       }
    
    
    
    
    
    
    
    
    
    
    
    //////////////////////////////////////////////////////////////////////
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        image2 = new javax.swing.JLabel();
        image1 = new javax.swing.JLabel();
        showtime = new javax.swing.JLabel();
        showdate = new javax.swing.JLabel();
        BackgroundImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagers/logo.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(270, 0, 290, 100);

        jLabel3.setFont(new java.awt.Font("Minion Pro SmBd", 2, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 51, 255));
        jLabel3.setText("Welcome to ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 30, 250, 60);

        jButton1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jButton1.setText("Members");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(40, 490, 140, 50);

        jButton2.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jButton2.setText("Books");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(220, 490, 140, 50);

        jButton3.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 12)); // NOI18N
        jButton3.setText("ReturnBook");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(420, 490, 150, 50);

        jButton4.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 12)); // NOI18N
        jButton4.setText("BarrowBook");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(660, 490, 150, 50);

        image2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagers/image4.jpg"))); // NOI18N
        image2.setText("jLabel5");
        jPanel1.add(image2);
        image2.setBounds(10, 100, 820, 360);

        image1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagers/image4.jpg"))); // NOI18N
        jPanel1.add(image1);
        image1.setBounds(10, 100, 820, 360);

        showtime.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        showtime.setText("..");
        jPanel1.add(showtime);
        showtime.setBounds(690, 10, 130, 30);

        showdate.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        showdate.setText("..");
        jPanel1.add(showdate);
        showdate.setBounds(680, 50, 150, 30);

        BackgroundImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagers/bkground.jpg"))); // NOI18N
        jPanel1.add(BackgroundImg);
        BackgroundImg.setBounds(0, 0, 850, 550);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 846, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Members obj = new Members();
        obj.setVisible(true);
        dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
         Books obj = new Books();
        obj.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ReturnBooks obj = new ReturnBooks();
        obj.setVisible(true);
        dispose();
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
              BarrowBook obj = new BarrowBook();
              obj.setVisible(true);
                 dispose();
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibaryHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibaryHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibaryHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibaryHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibaryHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundImg;
    private javax.swing.JLabel image1;
    private javax.swing.JLabel image2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel showdate;
    private javax.swing.JLabel showtime;
    // End of variables declaration//GEN-END:variables
}
